import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/features/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <div className=" h-52 bg-gradient-to-b from-[#cdefdc] to-[#FFFFFF]">

      <Navbar />
        {children}
        </div>

      </body>

    </html>
  );
}
