import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/features/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <div className="container xl:w-10/12  p-6 mx-auto">
      
      <Navbar />
        {children}
        </div>
      </body>
    </html>
  );
}
